version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
    - 16.9.4
  - dependency-name: nunit
    versions:
    - 3.13.1
