# YAML build definition for this app
# This file is needed only when you want to model your build definitions using YAML
queue: 
  name: Hosted Linux Preview
  
steps:
- task: dotNetCoreCLI@1
  inputs:
    command: restore
    projects: "reactive-extensions-test-core/*.csproj"
  displayName: dotnet restore

- task: dotNetCoreCLI@1
  inputs:
    command: build
    projects: "reactive-extensions-test-core/*.csproj"
    arguments: --configuration release
  displayName: dotnet build

- task: dotNetCoreCLI@1
  inputs:
    command: test 
    projects: "reactive-extensions-test-core/*.csproj"
    arguments: --configuration release
  displayName: dotnet test


- task: dotNetCoreCLI@1
  inputs:
    command: publish
    arguments: --configuration release --output "$(Build.ArtifactStagingDirectory)"
    zipAfterPublish: true
  displayName: dotnet publish

- task: publishBuildArtifacts@1
  inputs:
    PathtoPublish: "$(Build.ArtifactStagingDirectory)"
    ArtifactName: drop
    ArtifactType: Container
  displayName: Publish the artifacts