queue:  Hosted Linux Preview

variables: 
  BuildConfiguration: Release
  
steps:

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: reactive-extensions/*.csproj
    configuration: $(BuildConfiguration)
    packDirectory: $(Build.ArtifactStagingDirectory)\artifacts    
    verbosityPack: Minimal
  displayName: Pack

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: reactive-extensions-test/*.csproj
    arguments: -c $(BuildConfiguration)   
  displayName: Run Tests

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\artifacts
    artifactType: container
    artifactName: Packages
  condition: eq(variables['system.pullrequest.isfork'], false)